---
# tasks file for major

# - name: aaaaaa
#   become: yes
#   shell: "ln -sfn /usr/bin/python2.6 /usr/bin/python"

# - name: aaaaaaaaa
#   yum:
#     name: python2-psycopg2
#     state: present

- name: download postgresql rpm packet
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: install postgresql
  yum:
    name: postgresql14-server
    state: present

- name: check initialization db
  stat:
    path: "{{pgpath}}/postgresql.conf"
  register: stat_result

- name: initialize db
  become_user: postgres
  shell: "/usr/pgsql-14/bin/initdb -D {{pgpath}}"
  when: not stat_result.stat.exists

- name: check wal
  stat:
    path: /wal
  register: stat_result

- name: create wal directory
  file:
    path: /wal
    state: directory
    owner: postgres
  when: not stat_result.stat.exists

- name: new postgresql.conf from files
  copy:
    src: postgresql.conf
    dest: "{{pgpath}}/postgresql.conf"
  notify:
    - restart postgresql-14

- name: new pg_hba.conf from files
  copy:
    src: pg_hba.conf
    dest: "{{pgpath}}/pg_hba.conf"
  notify:
    - restart postgresql-14

- name: "Start and enable services"
  service: "name={{item}} state=started enabled=yes"
  with_items:
    - postgresql-14

- name: create app db
  postgresql_db:
    state: present
    name: "{{db_name}}"
  become: yes
  become_user: postgres

- name: create db user
  postgresql_user:
    state: present
    name: "{{db_user}}"
    password: "{{db_password}}"
    role_attr_flags: replication
  become: yes
  become_user: postgres
